@startuml
' -- bewusst minimal für breite Kompatibilität --
hide footbox
skinparam shadowing false
skinparam defaultFontName Arial
skinparam sequenceParticipantFontSize 14
skinparam sequenceActorFontSize 14
skinparam sequenceArrowFontSize 14
'skinparam maxMessageSize 40
actor "SPS (OPC UA)" as SPS
participant ":PLC\nMonitor" as PLCM
participant ":Inventory\nSnapshot\nUtils" as InvU
participant ":EventBus" as Bus
participant ":Reaction\nManager" as RM
participant ":Command\nForce\nFactory" as CFF
participant ":ICommand\nForce" as ICF
participant ":Failure\nRecorder" as FR
participant ":Time\nBlogger" as TB
participant ":Ack\nLogger" as AL

== Trigger==
SPS -> PLCM : TriggerD2 = TRUE
PLCM -> PLCM : post build-snapshot task
PLCM -> InvU : buildInventorySnapshotNow("PLC")
InvU --> PLCM : InventorySnapshot
PLCM -> Bus : post evD2 (correlationId, snapshot)
==Dispatch==
Bus -> RM : onEvent(evD2)
Bus -> FR : onEvent(evD2)
Bus -> TB : onEvent(evD2)
@enduml
