@startuml
' -- bewusst minimal für breite Kompatibilität --
hide footbox
skinparam shadowing false
skinparam defaultFontName Arial
skinparam sequenceParticipantFontSize 14
skinparam sequenceActorFontSize 14
skinparam sequenceArrowFontSize 14
'skinparam maxMessageSize 40
actor "SPS (OPC UA)" as SPS
participant ":PLC\nMonitor" as PLCM
participant ":Inventory\nSnapshot\nUtils" as InvU
participant ":EventBus" as Bus
participant ":Reaction\nManager" as RM
participant ":Command\nForce\nFactory" as CFF
participant ":ICommand\nForce" as ICF
participant ":Failure\nRecorder" as FR
participant ":Time\nBlogger" as TB
participant ":Ack\nLogger" as AL

==Plan and Execute==
RM -> RM : normalize / compare / buildPlan
RM -> CFF : createCommandForceForPlanAndAck(plan)
CFF -> ICF : createForOp(op, mon, bus)
ICF -> Bus : post evSRPlanned (corr)
Bus -> AL : onEvent(evSRPlanned)

ICF -> ICF : execute(plan)
ICF -> Bus : post evSRDone (rc) or evProcessFail
Bus -> AL : onEvent(evSRDone / evProcessFail)
Bus -> TB : onEvent(...)

==KG Ingestion==
Bus -> FR : onEvent(evSRDone / evProcessFail)
FR -> CFF : createForOp(KGIngestion, ..., bus)
CFF -> ICF : KGIngestionForce
ICF -> Bus : post evIngestionPlanned (corr)
Bus -> AL : onEvent(evIngestionPlanned)
ICF -> Bus : post evIngestionDone (corr, rc)
Bus -> AL : onEvent(evIngestionDone)
Bus -> TB : onEvent(...)
TB -> TB : finish(corr)


@enduml
