<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MBS_DmPD_AS_RotationMove" Id="{07f10f18-efa3-42d2-aa6b-804a1b000c93}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'OPC.UA.DA.JobMethod' := 'JobMethode_RotationMove'}
FUNCTION_BLOCK MBS_DmPD_AS_RotationMove
VAR
	AlwaysTrue : BOOL := TRUE;
	// Used for debugging purposes to display InputArguments of method call
	MethodCall_RotationMove : BOOL := FALSE; // used to store InputArg "MethodCall" from Start() method
	Direction : BOOL := FALSE;
	//	TS_EndschalterEntlastung : BOOL;
	callCounterStart : ULINT; // counts how many times the Start() method has been called
	callCounterCheckState : ULINT; // counts how many times the CheckState() method has been called
	callCounterAbort : ULINT; // counts how many times the Abort() method has been called
	
	// Variables to determine if a job has been started (Start() method has been called) or finished
	jobRunning : BOOL;
	jobFinished : BOOL;

	// State machine variable
	state : UDINT;
	
	//Variablen des Transport FBs
	ResetCall : BOOL := FALSE;	
	MBS_PD_RotationMove : AxisControl_MultipleInputSensors;
END_VAR
	
VAR_INPUT
	NotAusSignal: BOOL;
	LightSensor_01 : BOOL;
	LightSensor_02 : BOOL;
	TS_Endschalter_01 : BOOL;
	TS_Endschalter_02 : BOOL;
	TOF_Time_Motoransteuerung : TIME;
	TOF_Time_EndschalterEntlastung : TIME;
END_VAR

VAR_OUTPUT
	Motor_Ansteuerung01 : BOOL;
	Motor_Ansteuerung02 : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Fbd"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"EXECUTE"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">1563L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"AlwaysTrue"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">469L</v>
                          </o>
                          <v n="Id">468L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">None</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <o n="STSnippet" t="STSnippet">
                        <o n="STSnippet" t="STImplementationObject">
                          <o n="TextDocument" t="TextDocument">
                            <a n="TextLines" cet="TextLine">
                              <o>
                                <v n="Id">1564L</v>
                                <n n="Tag" />
                                <v n="Text">"CASE state OF"</v>
                              </o>
                              <o>
                                <v n="Id">1565L</v>
                                <n n="Tag" />
                                <v n="Text">"	0:"</v>
                              </o>
                              <o>
                                <v n="Id">1566L</v>
                                <n n="Tag" />
                                <v n="Text">"		IF jobRunning THEN"</v>
                              </o>
                              <o>
                                <v n="Id">1567L</v>
                                <n n="Tag" />
                                <v n="Text">"			state := state + 1;"</v>
                              </o>
                              <o>
                                <v n="Id">1568L</v>
                                <n n="Tag" />
                                <v n="Text">"		END_IF"</v>
                              </o>
                              <o>
                                <v n="Id">1569L</v>
                                <n n="Tag" />
                                <v n="Text">"		"</v>
                              </o>
                              <o>
                                <v n="Id">1570L</v>
                                <n n="Tag" />
                                <v n="Text">"	1:"</v>
                              </o>
                              <o>
                                <v n="Id">1571L</v>
                                <n n="Tag" />
                                <v n="Text">"		IF ResetCall THEN"</v>
                              </o>
                              <o>
                                <v n="Id">1572L</v>
                                <n n="Tag" />
                                <v n="Text">"			jobRunning := FALSE;"</v>
                              </o>
                              <o>
                                <v n="Id">1573L</v>
                                <n n="Tag" />
                                <v n="Text">"			jobFinished := TRUE;"</v>
                              </o>
                              <o>
                                <v n="Id">1574L</v>
                                <n n="Tag" />
                                <v n="Text">"			state := 0;"</v>
                              </o>
                              <o>
                                <v n="Id">1575L</v>
                                <n n="Tag" />
                                <v n="Text">"			MethodCall_RotationMove := FALSE;"</v>
                              </o>
                              <o>
                                <v n="Id">1576L</v>
                                <n n="Tag" />
                                <v n="Text">"		END_IF"</v>
                              </o>
                              <o>
                                <v n="Id">1577L</v>
                                <n n="Tag" />
                                <v n="Text">"		"</v>
                              </o>
                              <o>
                                <v n="Id">1578L</v>
                                <n n="Tag" />
                                <v n="Text">"END_CASE"</v>
                              </o>
                              <o>
                                <v n="Id">1547L</v>
                                <n n="Tag" />
                                <v n="Text">""</v>
                              </o>
                            </a>
                          </o>
                        </o>
                        <v n="Id">1579L</v>
                      </o>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">true</v>
                      <v n="Id">1580L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">30L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Motor_Ansteuerung01"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">1041L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"AxisControl_MultipleInputSensors"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"MBS_PD_RotationMove"</v>
                          <v n="Type">"AxisControl_MultipleInputSensors"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">1581L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"Motor_Ansteuerung02"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">976L</v>
                            </o>
                            <o>
                              <v n="Operand">"ResetCall"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">977L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"MethodCall_RotationMove"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">979L</v>
                            </o>
                            <v n="Id">978L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"NotAusSignal"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">983L</v>
                            </o>
                            <v n="Id">982L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"Direction"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1584L</v>
                            </o>
                            <v n="Id">1583L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1052L</v>
                            </o>
                            <v n="Id">1051L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1054L</v>
                            </o>
                            <v n="Id">1053L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TS_Endschalter_01"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1056L</v>
                            </o>
                            <v n="Id">1055L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TS_Endschalter_02"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1058L</v>
                            </o>
                            <v n="Id">1057L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"_REFACTOR_"</v>
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1623L</v>
                            </o>
                            <v n="Id">1622L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1334L</v>
                            </o>
                            <v n="Id">1333L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1108L</v>
                            </o>
                            <v n="Id">1107L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1110L</v>
                            </o>
                            <v n="Id">1109L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>MethodCall</v>
                            <v>NotAus_Signal</v>
                            <v>Direction</v>
                            <v>LightSensor_01</v>
                            <v>LightSensor_02</v>
                            <v>TS_Endschalter_01</v>
                            <v>TS_Endschalter_02</v>
                            <v>AutomaticMode</v>
                            <v>TS_EndschalterEntlastung</v>
                            <v>TOF_Time_Motoransteuerung</v>
                            <v>TOF_Time_EndschalterEntlastung</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>TIME</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Motor_Direction01</v>
                            <v>Motor_Direction02</v>
                            <v>ResetCall</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">1582L</v>
                      </o>
                      <v n="Id">1042L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">973L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="STImplementationObject">{3b83b776-fb25-43b8-99f2-3c507c9143fc}</Type>
            <Type n="String">System.String</Type>
            <Type n="STSnippet">{b2131366-6917-4304-87a9-64c0585560a8}</Type>
            <Type n="TextDocument">{f3878285-8e4f-490b-bb1b-9acbb7eb04db}</Type>
            <Type n="TextLine">{a5de0b0b-1cb5-4913-ac21-9d70293ec00d}</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Method Name="Abort" Id="{2e4c70dd-b300-45a1-918d-27604270f9c1}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD Abort : HRESULT
VAR_INPUT
	hdl : UDINT; // Do not change, used by server.
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[callCounterAbort := callCounterAbort + 1;]]></ST>
      </Implementation>
    </Method>
    <Method Name="CheckState" Id="{333d620e-5c50-48a5-a9e0-ae2b54e56024}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD CheckState : HRESULT
VAR_INPUT
	hdl : UDINT; // Do not change, used by server.
END_VAR
VAR_OUTPUT
	bBusy : BOOL; // Do not change. Used by server to find out if the job is finished
	
	// List of OutputArguments for OPC UA method, may be customized
	State : BOOL; // Abgeschlossener MethodCall
	MethodCall: BOOL; //Input Recall
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[callCounterCheckState := callCounterCheckState + 1;
IF NOT jobFinished THEN
	bBusy := TRUE; // job is not finished yet
	CheckState := 0; // no error
ELSE
	bBusy := FALSE; // job is finished
	CheckState := 0; // done, no error occured during execution (OPC UA StatusCode "GOOD")
	jobFinished := FALSE;
	State := ResetCall;
	MethodCall := MethodCall_RotationMove;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{65e88dfc-2a01-4ac2-ba5f-eec3d6372e46}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD Start : HRESULT
VAR_INPUT
	// List of InputArguments for OPC UA method, may be customized
	MethodCall : BOOL; // some description
	DirectionPoint : BOOL;
//	EndschalterEntlastung : BOOL;		
END_VAR
VAR_OUTPUT
	hdl : UDINT; // Do not change, used by server.
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[callCounterStart := callCounterStart + 1;

MethodCall_RotationMove := MethodCall;
DirectionPoint := Direction;
//EndschalterEntlastung := EndschalterEntlastung;

jobRunning := TRUE;
Start := 0; // no error occured, e.g. while parsing the input arguments (0 = OPC UA StatusCode "GOOD")]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="MBS_DmPD_AS_RotationMove.Abort">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="MBS_DmPD_AS_RotationMove.CheckState">
      <LineId Id="29" Count="7" />
      <LineId Id="39" Count="0" />
      <LineId Id="53" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="MBS_DmPD_AS_RotationMove.Start">
      <LineId Id="16" Count="0" />
      <LineId Id="18" Count="1" />
      <LineId Id="34" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>