<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_MyOpcUaMethod" Id="{fd6aedc3-3cae-4807-bc00-d82107da6d27}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_MyOpcUaMethod
VAR_INPUT
	in1 : INT;
	in2 : INT;
END_VAR
VAR_OUTPUT
	result : INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Multiply" Id="{bacdc101-7811-4568-b8f7-d894b6cac98a}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD PUBLIC Multiply : INT
VAR_INPUT
	a : INT;
	b : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Multiply := a * b;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_MyOpcUaMethod">
      <LineId Id="26" Count="0" />
    </LineIds>
    <LineIds Name="FB_MyOpcUaMethod.Multiply">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>