<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="HRL_CB_AS_HorizontalMove" Id="{e5740522-dfa1-4a36-b236-0740e0d326ba}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'OPC.UA.DA.JobMethod' := 'JobMethode_HorizontalMove'}
FUNCTION_BLOCK HRL_CB_AS_HorizontalMove
VAR
	AlwaysTrue : BOOL := TRUE;
	// Used for debugging purposes to display InputArguments of method call
	MethodCall_HorizontalMove : BOOL := FALSE; // used to store InputArg "MethodCall" from Start() method
	ResetMethodCall	: BOOL := FALSE;
	Direction : BOOL := FALSE; // defines movement direction
	callCounterStart : ULINT; // counts how many times the Start() method has been called
	callCounterCheckState : ULINT; // counts how many times the CheckState() method has been called
	callCounterAbort : ULINT; // counts how many times the Abort() method has been called
	
	// Variables to determine if a job has been started (Start() method has been called) or finished
	jobRunning : BOOL;
	jobFinished : BOOL;

	// State machine variable
	state : UDINT;
	
	// FB Intatziation Variable
	HRL_CB_HorizontalMove : AxisControl_MultipleInputSensors;
END_VAR
	
VAR_INPUT
	ESS: BOOL;
	LightBarrierSensor_01 : BOOL;
	LightBarrierSensor_02 : BOOL;
	AutomaticMode: BOOL;
END_VAR

VAR_OUTPUT
	Motor_Control : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Fbd"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"EXECUTE"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">1956L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"AlwaysTrue"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">1415L</v>
                          </o>
                          <v n="Id">1414L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">None</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <o n="STSnippet" t="STSnippet">
                        <o n="STSnippet" t="STImplementationObject">
                          <o n="TextDocument" t="TextDocument">
                            <a n="TextLines" cet="TextLine">
                              <o>
                                <v n="Id">1957L</v>
                                <n n="Tag" />
                                <v n="Text">"CASE state OF"</v>
                              </o>
                              <o>
                                <v n="Id">1958L</v>
                                <n n="Tag" />
                                <v n="Text">"	0:"</v>
                              </o>
                              <o>
                                <v n="Id">1959L</v>
                                <n n="Tag" />
                                <v n="Text">"		IF jobRunning THEN"</v>
                              </o>
                              <o>
                                <v n="Id">1960L</v>
                                <n n="Tag" />
                                <v n="Text">"			state := state + 1;"</v>
                              </o>
                              <o>
                                <v n="Id">1961L</v>
                                <n n="Tag" />
                                <v n="Text">"		END_IF"</v>
                              </o>
                              <o>
                                <v n="Id">1962L</v>
                                <n n="Tag" />
                                <v n="Text">"		"</v>
                              </o>
                              <o>
                                <v n="Id">1963L</v>
                                <n n="Tag" />
                                <v n="Text">"	1:"</v>
                              </o>
                              <o>
                                <v n="Id">1964L</v>
                                <n n="Tag" />
                                <v n="Text">"		IF ResetMethodCall THEN"</v>
                              </o>
                              <o>
                                <v n="Id">1965L</v>
                                <n n="Tag" />
                                <v n="Text">"			jobRunning := FALSE;"</v>
                              </o>
                              <o>
                                <v n="Id">1966L</v>
                                <n n="Tag" />
                                <v n="Text">"			jobFinished := TRUE;"</v>
                              </o>
                              <o>
                                <v n="Id">1967L</v>
                                <n n="Tag" />
                                <v n="Text">"			state := 0;"</v>
                              </o>
                              <o>
                                <v n="Id">1968L</v>
                                <n n="Tag" />
                                <v n="Text">"			MethodCall_HorizontalMove := FALSE;"</v>
                              </o>
                              <o>
                                <v n="Id">1969L</v>
                                <n n="Tag" />
                                <v n="Text">"		END_IF"</v>
                              </o>
                              <o>
                                <v n="Id">1970L</v>
                                <n n="Tag" />
                                <v n="Text">"		"</v>
                              </o>
                              <o>
                                <v n="Id">1971L</v>
                                <n n="Tag" />
                                <v n="Text">"END_CASE"</v>
                              </o>
                              <o>
                                <v n="Id">1940L</v>
                                <n n="Tag" />
                                <v n="Text">""</v>
                              </o>
                            </a>
                          </o>
                        </o>
                        <v n="Id">1972L</v>
                      </o>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">true</v>
                      <v n="Id">1973L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">47L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Motor_Control"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">1441L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"AxisControl_MultipleInputSensors"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"HRL_CB_HorizontalMove"</v>
                          <v n="Type">"AxisControl_MultipleInputSensors"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">1977L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1419L</v>
                            </o>
                            <o>
                              <v n="Operand">"ResetMethodCall"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1420L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"MethodCall_HorizontalMove"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1422L</v>
                            </o>
                            <v n="Id">1421L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"ESS"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1424L</v>
                            </o>
                            <v n="Id">1423L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"Direction"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1426L</v>
                            </o>
                            <v n="Id">1425L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"LightBarrierSensor_01"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1807L</v>
                            </o>
                            <v n="Id">1806L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"LightBarrierSensor_02"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1809L</v>
                            </o>
                            <v n="Id">1808L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1688L</v>
                            </o>
                            <v n="Id">1687L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1438L</v>
                            </o>
                            <v n="Id">1437L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"AutomaticMode"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1980L</v>
                            </o>
                            <v n="Id">1979L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1440L</v>
                            </o>
                            <v n="Id">1439L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>MethodCall</v>
                            <v>EmergencyStopSignal</v>
                            <v>Direction</v>
                            <v>Sensor_01</v>
                            <v>Sensor_02</v>
                            <v>TouchSensorRelief</v>
                            <v>TOF_Time_MotorControl</v>
                            <v>AutomaticMode</v>
                            <v>TOF_Time_TouchSensorRelief</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>TIME</v>
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>MotorControl_01</v>
                            <v>MotorControl_02</v>
                            <v>ResetCall</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">1978L</v>
                      </o>
                      <v n="Id">1442L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">1416L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="STImplementationObject">{3b83b776-fb25-43b8-99f2-3c507c9143fc}</Type>
            <Type n="String">System.String</Type>
            <Type n="STSnippet">{b2131366-6917-4304-87a9-64c0585560a8}</Type>
            <Type n="TextDocument">{f3878285-8e4f-490b-bb1b-9acbb7eb04db}</Type>
            <Type n="TextLine">{a5de0b0b-1cb5-4913-ac21-9d70293ec00d}</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Method Name="Abort" Id="{f5647571-a28f-4042-beec-29e749c636d5}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD Abort : HRESULT
VAR_INPUT
	hdl : UDINT; // Do not change, used by server.
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[callCounterAbort := callCounterAbort + 1;]]></ST>
      </Implementation>
    </Method>
    <Method Name="CheckState" Id="{060c9808-54d1-4d1e-ab68-457cc9b822f4}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD CheckState : HRESULT
VAR_INPUT
	hdl : UDINT; // Do not change, used by server.
END_VAR
VAR_OUTPUT
	bBusy : BOOL; // Do not change. Used by server to find out if the job is finished
	
	// List of OutputArguments for OPC UA method, may be customized
	State : BOOL; // Abgeschlossener MethodCall
	MethodCall: BOOL; //Input Recall
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[callCounterCheckState := callCounterCheckState + 1;
IF NOT jobFinished THEN
	bBusy := TRUE; // job is not finished yet
	CheckState := 0; // no error
ELSE
	bBusy := FALSE; // job is finished
	CheckState := 0; // done, no error occured during execution (OPC UA StatusCode "GOOD")
	jobFinished := FALSE;
	State := ResetMethodCall;
	MethodCall := MethodCall_HorizontalMove;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{5edcf620-8359-429a-9afe-262ce45d41b7}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD Start : HRESULT
VAR_INPUT
	// List of InputArguments for OPC UA method, may be customized
	MethodCall : BOOL; // some description
	MovementDirection : BOOL;	
END_VAR
VAR_OUTPUT
	hdl : UDINT; // Do not change, used by server.
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[callCounterStart := callCounterStart + 1;

MethodCall_HorizontalMove := MethodCall;
MovementDirection := Direction;

jobRunning := TRUE;
Start := 0; // no error occured, e.g. while parsing the input arguments (0 = OPC UA StatusCode "GOOD")]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="HRL_CB_AS_HorizontalMove.Abort">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HRL_CB_AS_HorizontalMove.CheckState">
      <LineId Id="29" Count="7" />
      <LineId Id="39" Count="0" />
      <LineId Id="53" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HRL_CB_AS_HorizontalMove.Start">
      <LineId Id="16" Count="0" />
      <LineId Id="18" Count="1" />
      <LineId Id="33" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>